const initialData=[
    {
        "key": "OL262556W",
        "title": "The history of spiritualism",
        "authors": "J.R.R. Tolkien",
        "genre": ["Spiritualism", "History", "Curiosities and wonders", "Spirituality"],
        "description": "The Scottish writer Sir Arthur Conan Doyle (1859-1930) is best known for his creation of the character Sherlock Holmes. Trained as a medical doctor, Doyle - like many Victorian intellectuals - became fascinated by spiritualism and its promise of communication with the afterlife. Doyle was a firm believer in the movement, claiming as evidence 'sign[s] of a purposeful and organized invasion' from the spirit world. In 1926, towards the end of his life, he published this influential two-volume history. Volume 2 focuses on celebrated mediums from 1870 to World War I and explores topics such as 'ectoplasm', 'spirit photography' and 'voice mediumship'. Doyle also discusses spiritualism as practised in Europe and the religious aspects of the movement. The History provides valuable insights into Victorian and early twentieth-century culture and the enthusiasm and controversies generated by spiritualism at that time.",
        "excerpts":"'Battle and war!' said Gandalf. 'Ride on!',This book is largely concerned with Hobbits, and from its pages a reader may discover much of their character and a little of their history.first sentence",
         "available":"true",
    },
        
        {
            "key": "OL1548597W",
            "title": "On the Nature of the Universe",
            "authors": "Titus Lucretius Carus",
            "genre": ["Poetry"],
            "description": "This is regarded as a seminal text of Epicurean science and philosophy. Epicurians discarded both the idea of immortality and the superstitious worship of wilful gods for a life of serene contentment in the available pleasures of nature. Lucretius (c100-c55BC), in elucidating this belief, steers the reader through an extraordinary breadth of subject matter, ranging from the indestructibility of atoms and the discovery of fire to the folly of romantic love and the phenomena of clouds and rainstorms.",
            "excerpts":" you are right now, outer space is only 62 miles (100 kilometers) away. Day or night, whether you’re indoors or outdoors, asleep, eating lunch or dozing off in class, ",
            "available":"true",
        
        },
        {
            "key": "OL4158858W",
            "title": "Karel Appel",
            "authors": "Karel Appel, Jean-Clarence Lambert, Kenneth White, Marshall McLahan, Johannes Gachnang, Donald Kuspit, and Jean Fremon",
            "genre": ["Exhibitions", "Painters","Art","Histor"],
            "description":"Juana Rosalia sueña con ser escritora. No duda en convertir la ficción en realidad, el problema es que cada nota provoca situaciones imprevistas. Esta novela toca inquietudes de los adolescentes: el amor, la sexualidad, los tatuajes, a la vez que reflexiona sobre nuestros deseos y sus consecuencias.",
            "excerpts":"In fact, you’re technically in space right now. Humans say “out in space” as if it’s there and we’re here, as if Earth is separate from the rest of the universe.",
            "available":"true",
        
        },
        {
            "key": "OL82577W", 
            "title": "Harry Potter and the Goblet of Fire", 
            "authors": "J. K. Rowling",
            "genre": [ "Fiction"], 
            "description": "The fourth book in the Harry Potter franchise sees Harry returning for his fourth year at Hogwarts School of Witchcraft and Wizardry, along with his friends, Ron and Hermione . There is an upcoming tournament between the three major schools of magic, with one participant selected from each school by the Goblet of Fire. When Harry's name is drawn, even though he is not eligible and is a fourth player, he must compete in the dangerous contest.", 
            "excerpts": "The villagers of Little Hangleton still called it 'the Riddle House,' even though it had been many years since the Riddle family had lived there.", 
            "available":"true",
        
        },
        {
        "key": "OL80592W",
        "title": "Les confessions",
         "authors": "Jean-Jacques Rousseau",
         "genre": [ "Classic Literature", "Fiction", "Philosophers", "Autobiography"],
         "description": "Je forme une entreprise qui n'eut jamais d'exemple, et dont l'execution n'aura point d'imitateur. Je veux montrer a mes semblables un homme dans toute la verite de la nature; et cet homme, ce sera moi. Moi seul. Je sens mon coeur, et je connais les hommes. Je ne suis fait comme aucun de ceux que j'ai vus; j'ose croire n'etre fait comme aucun de ceux qui existent. Si je ne vaux pas mieux, au moins je suis autre. Si la nature a bien ou mal fait de briser le moule dans lequel elle m'a jete, c'est ce dont on ne peut juger qu'apres m'avoir lu. Que la trompette du jugement dernier sonne quand elle voudra, je viendrai, ce livre a la main, me presenter devant le souverain juge. Je dirai hautement: Voila ce que j'ai fait, ce que j'ai pense, ce que je fus. J'ai dit le bien et le mal avec la meme franchise. Je n'ai rien tu de mauvais, rien ajoute de bon; et s'il m'est arrive d'employer quelque ornement indifferent, ce n'a jamais ete que pour remplir un vide occasionne par mon defaut de memoire. J'ai pu supposer vrai ce que je savais avoir pu l'etre, jamais ce que je savais etre faux. Je me suis montre tel que je fus: meprisable et vil quand je l'ai ete; bon, genereux, sublime, quand je l'ai ete: j'ai devoile mon interieur tel que tu l'as vu toi-meme. Etre eternel, rassemble autour de moi l'innombrable foule de mes semblables; qu'ils ecoutent mes confessions, qu'ils gemissent de mes indignites, qu'ils rougissent de mes miseres. Que chacun d'eux decouvre a son tour son coeur au pied de ton trone avec la meme sincerite, et puis qu'un seul te dise, s'il l'ose: je fus meilleur que cet homme-la.",
         "excerpts": "I have resolved on an enterprise which has no precedent and which, once complete, will have no imitator. My purpose is to display to my kind a portrait in every way true to nature, and the man I shall portray will be myself.",
         "available":"true",
        }
        
        
        
        
        
        
        
        
        
]
export default initialData
